using System;
using System.Collections.Generic;
using System.Text;

namespace Business.Models;

public class Product
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public double Price { get; set; }
}

/* File generated by Gemini 3 Pro */
