using Business.Models;
using Microsoft.EntityFrameworkCore;

namespace Data.Context;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

    public DbSet<Product> Products => Set<Product>();

    // 👇 THIS IS THE FIX
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("products");           // Map to lowercase table
            entity.Property(e => e.Id).HasColumnName("id");       // Map to lowercase 'id'
            entity.Property(e => e.Name).HasColumnName("name");   // Map to lowercase 'name'
            entity.Property(e => e.Price).HasColumnName("price"); // Map to lowercase 'price'
        });
    }
}
/* File generated by Gemini 3 Pro */